name: 🐛 Bug Report
description: I think I've discovered a bug or other issue.
title: "[BUG]: "
labels: "bug"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe your issue in as much detail as possible. For example: What happened? What did you expect to happen?
      placeholder: Description
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: |
        What should PHG V2 be doing differently?

  - type: input
    id: version
    attributes:
      label: PHG version
      description: Check the release number.
      placeholder: ex. 2.0.2.10
