name: Run Deployment When Pushing to Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: PHGv2 Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # See: https://github.com/mikepenz/action-junit-report/issues/23#issuecomment-1412597753
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.4.2
          generate-job-summary: false
      - run: gradle build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_name: BioKotlin Test Report
          job_summary: true
          detailed_summary: true
